services:
  bms.webmvc:
    container_name: bms-webmvc
    image: bms.webmvc
    build:
      context: .
      dockerfile: BMS.WebMVC/Dockerfile
    ports:
      - "80:8080"
  bms.database:
    container_name: bms-database
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1*
    ports:
      - "1433:1433"
